// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace StockTradingApp.Models
{
    public partial class sliceofbreadContext : DbContext
    {
        public sliceofbreadContext()
        {
        }

        public sliceofbreadContext(DbContextOptions<sliceofbreadContext> options)
            : base(options)
        {
        }

        public virtual DbSet<StockData> StockData { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //should probably protect this...
                optionsBuilder.UseSqlServer("Data Source=sliceofbread.database.windows.net;Initial Catalog=sliceofbread;Persist Security Info=True;User ID=Boss;Password=Makers.$bench.mark");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}