// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StockTradingApp.Models
{
    [Table("StockData", Schema = "stonks")]
    public partial class StockData
    {
        public int index { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string ticker { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string date { get; set; }
        [Column(TypeName = "decimal(30, 5)")]
        public decimal open { get; set; }
        [Column(TypeName = "decimal(30, 5)")]
        public decimal close { get; set; }
        [Column(TypeName = "decimal(30, 5)")]
        public decimal high { get; set; }
        [Column(TypeName = "decimal(30, 5)")]
        public decimal low { get; set; }
        public long volume { get; set; }
        [Column(TypeName = "decimal(30, 5)")]
        public decimal adjClose { get; set; }
        [Key]
        public int ID { get; set; }
    }
}